
openapi: '3.0'
info:
  title: Apertium Stats Service
  version: '0.1.0'
  description: Rust web service that enables the efficient parallel compilation and
    distribution of statistics regarding Apertium packages via a RESTful API.
servers:
  - url: http://localhost:8000
    description: Development
paths:
  /:
    get:
      summary: Returns usage instructions
      responses:
        '200':
            description: Usage instructions
            content:
              text/plain: {}
  /{package}:
    parameters:
      - $ref: '#/components/parameters/Package'
    get:
      summary: Returns statistics for the specified package
      responses:
        '200':
          description: Statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  stats:
                    $ref: '#/components/schemas/Stats'
        # TODO: rest of the responses
  # TODO: rest of the paths
components:
  parameters:
    Package:
      name: package
      in: path
      required: true
      description: package identifier
      example: apertium-pl-dsb
      schema:
        type: string
  schemas:
    StatKind:
      type: string
      enum:
        - stems
        - paradigms
        - rules
        - macros
    Stats:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            example: apertium-pl-dsb
          path:
            type: string
            example: apertium-pl-dsb.pl-dsb.dix
          revision:
            type: string
            example: 13
          kind:
            $ref: '#components/schemas/StatKind'
            example: stems
          value:
            type: string
            example: 366
