
openapi: '3.0'
info:
  title: Apertium Stats Service
  version: '0.1.0'
  description: Stateful Rust web service that enables the efficient parallel compilation
    and distribution of statistics regarding Apertium packages via a RESTful API.
servers:
  - url: http://localhost:8000
    description: Development
paths:
  /:
    get:
      summary: Returns usage instructions
      responses:
        '200':
            description: Usage instructions
            content:
              text/plain: {}
  /{package}:
    parameters:
      - $ref: '#/components/parameters/Package'
    get:
      summary: Returns statistics for the specified package
      responses:
        '200':
          description: Package statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  stats:
                    $ref: '#/components/schemas/Stats'
                  in_progress:
                    $ref: '#/components/schemas/StatsInProgress'
        '202':
          description: Package statistics in progress
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    example: apertium-pl-dsb
                    type: string
                  in_progress:
                    $ref: '#/components/schemas/StatsInProgress'
        '429':
          description: Package statistics already in progress
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    example: apertium-pl-dsb
                    type: string
                  in_progress:
                    $ref: '#/components/schemas/StatsInProgress'
        '400':
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Package not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
  # TODO: rest of the paths
components:
  parameters:
    Package:
      name: package
      in: path
      required: true
      description: package identifier
      example: apertium-pl-dsb
      schema:
        type: string
  schemas:
    Error:
      type: object
      properties:
        name:
          example: apertium-pl-dsb
          type: string
        error:
          example: No recognized files
          type: string
    StatKind:
      type: string
      enum:
        - stems
        - paradigms
        - rules
        - macros
    FileKind:
      type: string
      enum:
        - Monodix
        - Bidix
        - MetaMonodix
        - MetaBidix
        - Postdix
        - Rlx
        - Transfer
        - Lexc
        - Twol
    Stats:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            example: apertium-pl-dsb
          path:
            type: string
            example: apertium-pl-dsb.pl-dsb.dix
          revision:
            type: string
            example: 13
          kind:
            $ref: '#components/schemas/StatKind'
            example: stems
          value:
            type: string
            example: 366
          created:
            type: string
            format:	date-time
          requested:
            type: string
            format:	date-time
    StatsInProgress:
      type: array
      items:
        type: object
        properties:
          kind:
            $ref: '#components/schemas/FileKind'
          created:
            type: string
            format:	date-time
          path:
            type: string
            example: apertium-pl-dsb.pl-dsb.dix
          revision:
            type: string
            example: 13
